apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: canvas-app
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"