apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canvas-mongodb
  labels:
    app: canvas-mongodb
    component: database
spec:
  serviceName: canvas-mongodb-headless
  replicas: 3
  selector:
    matchLabels:
      app: canvas-mongodb
  template:
    metadata:
      labels:
        app: canvas-mongodb
        component: database
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: canvas-secrets
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: canvas-secrets
              key: mongodb-password
        - name: MONGO_INITDB_DATABASE
          value: "canvas_orchestration"
        command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip_all
        - --auth
        - --keyFile
        - /data/replica.key
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /data/configdb
        - name: mongodb-key
          mountPath: /data/replica.key
          subPath: replica.key
          readOnly: true
        - name: mongodb-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          fsGroup: 999
      volumes:
      - name: mongodb-key
        secret:
          secretName: mongodb-key-secret
          defaultMode: 0600
      - name: mongodb-init
        configMap:
          name: mongodb-init-script
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: canvas-ssd-storage
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: mongodb-config
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: canvas-ssd-storage
      resources:
        requests:
          storage: 1Gi