apiVersion: v2
name: canvas-orchestration
description: A Helm chart for Canvas AI Orchestration Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - orchestration
  - canvas
  - nestjs
  - mongodb
  - redis
  - opensearch
home: https://github.com/your-org/canvas-orchestration
sources:
  - https://github.com/your-org/canvas-orchestration
maintainers:
  - name: Canvas Team
    email: team@yourdomain.com
dependencies:
  - name: mongodb
    version: "13.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: opensearch
    version: "2.x.x"
    repository: "https://opensearch-project.github.io/helm-charts/"
    condition: opensearch.enabled
  - name: prometheus
    version: "15.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled