apiVersion: v1
kind: Service
metadata:
  name: canvas-redis-service
  labels:
    app: canvas-redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: canvas-redis
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-redis-headless
  labels:
    app: canvas-redis
    component: cache
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  - port: 16379
    targetPort: 16379
    protocol: TCP
    name: cluster-bus
  selector:
    app: canvas-redis