apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canvas-orchestration.fullname" . }}
  labels:
    {{- include "canvas-orchestration.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "canvas-orchestration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "canvas-orchestration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canvas-orchestration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            {{- if .Values.secrets.create }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: mongodb-uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: redis-url
            - name: OPENSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: opensearch-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: aws-secret-access-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "canvas-orchestration.fullname" . }}-secrets
                  key: jwt-secret
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "canvas-orchestration.fullname" . }}-config
          volumeMounts:
            {{- if .Values.persistence.uploads.enabled }}
            - name: uploads
              mountPath: /app/uploads
            {{- end }}
            {{- if .Values.persistence.logs.enabled }}
            - name: logs
              mountPath: /app/logs
            {{- end }}
            {{- if .Values.persistence.plugins.enabled }}
            - name: plugins-external
              mountPath: /app/plugins-external
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.uploads.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "canvas-orchestration.fullname" . }}-uploads
        {{- end }}
        {{- if .Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "canvas-orchestration.fullname" . }}-logs
        {{- end }}
        {{- if .Values.persistence.plugins.enabled }}
        - name: plugins-external
          persistentVolumeClaim:
            claimName: {{ include "canvas-orchestration.fullname" . }}-plugins
        {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}