apiVersion: v1
kind: Service
metadata:
  name: canvas-app-service
  labels:
    app: canvas-app
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: canvas-app
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-app-headless
  labels:
    app: canvas-app
    component: backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: canvas-app