apiVersion: v1
kind: Service
metadata:
  name: canvas-mongodb-service
  labels:
    app: canvas-mongodb
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: canvas-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: canvas-mongodb-headless
  labels:
    app: canvas-mongodb
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: canvas-mongodb