apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  labels:
    app: canvas-opensearch
data:
  opensearch.yml: |
    cluster.name: canvas-cluster

    # Node settings
    node.name: ${node.name}
    node.data: true
    node.master: true
    node.ingest: true
    node.search.remote.connect: false

    # Network settings
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300

    # Discovery settings
    discovery.seed_hosts: ["canvas-opensearch-0.canvas-opensearch-headless:9300", "canvas-opensearch-1.canvas-opensearch-headless:9300", "canvas-opensearch-2.canvas-opensearch-headless:9300"]
    cluster.initial_cluster_manager_nodes: ["canvas-opensearch-0", "canvas-opensearch-1", "canvas-opensearch-2"]

    # Memory settings
    bootstrap.memory_lock: true

    # Security settings
    plugins.security.disabled: false
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.transport.pemcert_filepath: certs/esnode.pem
    plugins.security.ssl.transport.pemkey_filepath: certs/esnode-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.pemcert_filepath: certs/esnode.pem
    plugins.security.ssl.http.pemkey_filepath: certs/esnode-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,L=test,C=de
    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices:
      [
        ".opendistro-alerting-config",
        ".opendistro-alerting-alert*",
        ".opendistro-anomaly-results*",
        ".opendistro-anomaly-detector*",
        ".opendistro-anomaly-checkpoints",
        ".opendistro-anomaly-detection-state",
        ".opendistro-reports-*",
        ".opendistro-notifications-*",
        ".opendistro-notebooks",
        ".opendistro-asynchronous-search-response*",
      ]

    # Index settings
    action.destructive_requires_name: true

    # Thread pool settings
    thread_pool.write.queue_size: 1000
    thread_pool.search.queue_size: 1000

    # Cluster settings
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: 85%
    cluster.routing.allocation.disk.watermark.high: 90%
    cluster.routing.allocation.disk.watermark.flood_stage: 95%
    cluster.info.update.interval: 1m

    # Performance settings
    indices.memory.index_buffer_size: 20%
    indices.memory.min_index_buffer_size: 96mb
    indices.fielddata.cache.size: 40%
    indices.queries.cache.size: 10%

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-jvm-config
  labels:
    app: canvas-opensearch
data:
  jvm.options: |
    # OpenSearch JVM configuration for Kubernetes

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space
    -Xms2g
    -Xmx2g

    # GC Configuration
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32m
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=50
    -XX:+UseStringDeduplication

    # GC logging
    -Xlog:gc*,gc+age=trace,safepoint:gc.log:utctime,pid,tid,level,tags
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=32
    -XX:GCLogFileSize=64m

    # Heap dumps
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/share/opensearch/data

    # JVM bug workarounds
    -XX:+UnlockDiagnosticVMOptions
    -XX:+LogVMOutput
    -XX:LogFile=/usr/share/opensearch/data/jvm.log

    # File encoding
    -Dfile.encoding=UTF-8

    # Use server-class machine detection
    -server

    # Disable calls to System#gc
    -XX:+DisableExplicitGC

    # Ensure UTF-8 encoding by default
    -Dfile.encoding=UTF-8

    # Use our provided JNA always versus the system one
    -Djna.nosys=true

    # Turn off a JDK optimization that throws away stack traces for common
    # exceptions because stack traces are important for debugging
    -XX:-OmitStackTraceInFastThrow

    # Flags to configure Netty
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dio.netty.allocator.numDirectArenas=0

    # Log4j 2 configuration
    -Dlog4j2.disable.jmx=true

    # Security manager
    -Djava.security.policy=opensearch.policy