apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: canvas-opensearch
  labels:
    app: canvas-opensearch
    component: search
spec:
  serviceName: canvas-opensearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: canvas-opensearch
  template:
    metadata:
      labels:
        app: canvas-opensearch
        component: search
    spec:
      terminationGracePeriodSeconds: 120
      initContainers:
      - name: configure-sysctl
        image: busybox:1.35
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/opensearch/data']
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        securityContext:
          runAsUser: 0
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: "canvas-cluster"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "canvas-opensearch-0.canvas-opensearch-headless,canvas-opensearch-1.canvas-opensearch-headless,canvas-opensearch-2.canvas-opensearch-headless"
        - name: cluster.initial_cluster_manager_nodes
          value: "canvas-opensearch-0,canvas-opensearch-1,canvas-opensearch-2"
        - name: bootstrap.memory_lock
          value: "true"
        - name: "OPENSEARCH_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        - name: "DISABLE_INSTALL_DEMO_CONFIG"
          value: "true"
        - name: "DISABLE_SECURITY_PLUGIN"
          value: "false"
        - name: "OPENSEARCH_INITIAL_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: canvas-secrets
              key: opensearch-password
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        - name: opensearch-config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
          readOnly: true
        - name: opensearch-jvm
          mountPath: /usr/share/opensearch/config/jvm.options
          subPath: jvm.options
          readOnly: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
            scheme: HTTPS
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46T3BlblNlYXJjaDEyMyE="
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
            scheme: HTTPS
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46T3BlblNlYXJjaDEyMyE="
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
      volumes:
      - name: opensearch-config
        configMap:
          name: opensearch-config
      - name: opensearch-jvm
        configMap:
          name: opensearch-jvm-config
  volumeClaimTemplates:
  - metadata:
      name: opensearch-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: canvas-ssd-storage
      resources:
        requests:
          storage: 100Gi